[package]
name = "framework"
version = "0.1.0"
edition = "2024"

[dependencies]
services = { workspace = true }
types = { workspace = true }
api = { workspace = true }
database = { workspace = true }
utils = { workspace = true }
dirs = "6.0.0"

[lints]
workspace = true
