name: Rust

on:
  push:
    branches: [ "build_linux" ]
  pull_request:
    branches: [ "build_linux" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: target/x86_64-unknown-linux-gnu/release/lm_client
